version: "3.3"
services:
  sakai_database:
    command: --character-set-server=utf8
    container_name: sakai_database
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=sakai_password
      - MYSQL_DATABASE=sakai_database      
      - MYSQL_USER=sakai_user
      - MYSQL_PASSWORD=sakai_password
  sakai:
    build: .
    container_name: sakai
    depends_on:
      - sakai_database
    ports:
      - 8080:8080
